main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include
from menu import urls
# from main import views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models
from django.db.models.fields import BooleanField, CharField, FloatField

class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.nom

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request, 'main/index.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Pizza

# Create your views here.
# def home(request):
#     pizzas_str = ""
#     pizzas = Pizza.objects.all()
#     pizzas_names = list(pizza.nom for pizza in pizzas)
#     pizzas_price = list(pizza.prix for pizza in pizzas)
#     for i in range(len(pizzas)):
#         pizzas_str += pizzas_names[i] + " - " + str(pizzas_price[i]) + "€, "
#     print(pizzas_str)
#     return HttpResponse("My pizzas")

def index(request):
    pizzas = Pizza.objects.all().order_by('prix')
    return render(request, "menu/index.html", {"pizzas":pizzas})

def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by('prix')
    json = serializers.serialize('json', pizzas)
    return HttpResponse(json)

# def api_get_one_pizza(request):
#     pizza = Pizza.objects.get()

main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pizza Mama</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div id="main">
        <div class="centered">
            <a href="{% url 'menu:index' %}"><img id="main_logo" src="{% static 'main/images/main_logo.png' %}" alt="main_logo"></a>
            <a href="/menu" class="link_to_menu">Voir le menu</a>
        </div>


    </div>
</body>
</html>

menu/templates/menu/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pizza Mama - Menu</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <div id="main">
        <div>
            <a href="{% url 'main:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}" alt="small_logo"></a>
        </div>
        <div class="menu_title">
            <h1>Les pizzas</h1>
        </div>

        <div class="menu_list">
            {% for pizza in pizzas %}
                <div class="menu_list_item">
                    <span class="menu_list_title">
                        {{pizza.nom}}
                    </span>
                    <span class="menu_list_price">
                        {{pizza.prix | floatformat:2}}€
                    </span>
                    <span class="menu_list_ingredients">
                        {{pizza.ingredients}}
                    </span>
                    {% if pizza.vegetarienne %}
                        <span class="menu_list_badge">VÉGÉTARIENNE</span>
                    {% endif %}
                </div> 
            {% endfor %}
        </div>
    </div>
</body>
</html>